### ISSUE TITLE
Sentry support

### ISSUE THREAD

**Issue by vassilevsky** [flyerhzm/uniform_notifier#34]
Hi 🙂 Would you be interested in a PR that adds support for https://github.com/getsentry/raven-ruby ?

**Comment by flyerhzm** [comment]
@vassilevsky yes, sure, feel free to send a PR

**Comment by cmitz** [comment]
Is it me, or am I missing some documentation on how to use this sentry notifier? Normal rails exceptions are already being reported to sentry, so I'm wondering: is more configuration needed?
