### ISSUE TITLE
Add support for inline notifier

### ISSUE THREAD

**Issue by nicolas-besnard** [flyerhzm/uniform_notifier#36]
It can be really cumbersome to add a new notifier. Sometimes it's just a copy / paste of a previous code just by changing the library used to notify.

I was thinking about adding something like:

```ruby
UniforNotifier.add_available_notifier(MyCustomNotifier)
```

With `MyCustomNotifier` that implement a common interface whether you want to support `inline_notify` or `out_of_channel_notify`.

Any thought about this @flyerhzm ? I'm happy to do the required refactoring

**Comment by tpaulshippy** [comment]
Why was this closed? Does this exist?
