### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by nicolas-besnard** [flyerhzm/uniform_notifier#37]
Could you release a new version to add the Sentry adaptor? Might be nice to update https://github.com/flyerhzm/bullet too!

**Comment by nicolas-besnard** [comment]
@flyerhzm Any thought?

**Comment by flyerhzm** [comment]
@nicolas-besnard released uniform_notifier 1.11.0, no need to release bullet, you can update uniform_notifier any time without updating bullet
