### ISSUE TITLE
Drop the use of deprecated ruby-growl gem

### ISSUE THREAD

**Issue by utkarsh2102** [flyerhzm/uniform_notifier#58]
Hi,

https://github.com/flyerhzm/uniform_notifier/blob/5827f1e27b85c067f49e93ce2301d59bff47f857/uniform_notifier.gemspec#L20

The upstream of ruby-growl gem is dead and there are test failures (since it doesn't work with Ruby2.7). Can you perhaps drop their usage and find an alternative?

**Comment by mishina2228** [comment]
ruby-growl is fairly outdated, and Growl itself has already been retired.
https://github.com/growl/growl/#retirement
> Growl is a retired project, we couldn't think of another thing to change which would be substantial enough to bring out a new updated release.

I assume that not many people are using Growl now, so I think we can stop supporting Growl.

**Comment by flyerhzm** [comment]
@mishina2228 good to know, I'll drop Growl support soon.
